export interface Project {
  id: string
  title: string
  titleKo: string
  location: string
  locationKo: string
  year: string
  status: "completed" | "in-progress" | "planning"
  client: string
  clientKo: string
  area: string // 연면적
  use: string // 용도
  useKo: string // 용도 한글
  image: string
  images?: string[]
  description: string
  descriptionKo: string
  company: "ndb" | "snp" | "metalogic" | "joint"
  featured?: boolean
}

export const projects: Project[] = [
  // NDB Projects
  {
    id: "ndb-tower",
    title: "NDB Innovation Tower",
    titleKo: "NDB 이노베이션 타워",
    location: "Seoul, Korea",
    locationKo: "서울, 한국",
    year: "2024",
    status: "completed",
    client: "NDB Corporation",
    clientKo: "NDB 주식회사",
    area: "45,000 m²",
    use: "Office / Commercial",
    useKo: "오피스 / 상업시설",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop",
    description: "An eco-friendly office tower that brings nature into the city. Sustainable work environment achieved through vertical gardens and natural ventilation systems.",
    descriptionKo: "도심 속 자연을 담은 친환경 오피스 타워. 수직 정원과 자연 환기 시스템을 통해 지속 가능한 업무 환경을 구현했습니다.",
    company: "ndb",
    featured: true,
  },
  {
    id: "ndb-cultural",
    title: "Cultural Complex",
    titleKo: "문화복합센터",
    location: "Busan, Korea",
    locationKo: "부산, 한국",
    year: "2023",
    status: "completed",
    client: "Busan Metropolitan City",
    clientKo: "부산광역시",
    area: "28,500 m²",
    use: "Cultural / Exhibition",
    useKo: "문화 / 전시",
    image: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&h=600&fit=crop",
    description: "A cultural complex that embodies the identity of a maritime city. Features an exterior inspired by wave curves.",
    descriptionKo: "해양 도시의 정체성을 담은 문화복합시설. 파도의 곡선을 모티브로 한 외관이 특징입니다.",
    company: "ndb",
  },
  {
    id: "ndb-residence",
    title: "Riverside Residence",
    titleKo: "리버사이드 레지던스",
    location: "Incheon, Korea",
    locationKo: "인천, 한국",
    year: "2025",
    status: "in-progress",
    client: "Private",
    clientKo: "개인",
    area: "12,800 m²",
    use: "Residential",
    useKo: "주거",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    description: "A premium residential complex maximizing Han River views. Designed so every unit enjoys river views.",
    descriptionKo: "한강 조망을 극대화한 프리미엄 주거 단지. 모든 세대가 리버뷰를 향유할 수 있도록 설계되었습니다.",
    company: "ndb",
  },

  // SNP Projects
  {
    id: "snp-museum",
    title: "Contemporary Art Museum",
    titleKo: "현대미술관",
    location: "Daejeon, Korea",
    locationKo: "대전, 한국",
    year: "2024",
    status: "completed",
    client: "Daejeon City",
    clientKo: "대전시",
    area: "18,200 m²",
    use: "Museum / Gallery",
    useKo: "미술관 / 갤러리",
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&h=600&fit=crop",
    description: "A museum exploring the harmony of light and space. Natural light organically connects the exhibition spaces.",
    descriptionKo: "빛과 공간의 조화를 탐구한 미술관. 자연광이 전시 공간을 유기적으로 연결합니다.",
    company: "snp",
    featured: true,
  },
  {
    id: "snp-library",
    title: "Community Library",
    titleKo: "커뮤니티 도서관",
    location: "Sejong, Korea",
    locationKo: "세종, 한국",
    year: "2023",
    status: "completed",
    client: "Sejong City",
    clientKo: "세종시",
    area: "8,500 m²",
    use: "Library / Community",
    useKo: "도서관 / 커뮤니티",
    image: "https://images.unsplash.com/photo-1568667256549-094345857637?w=800&h=600&fit=crop",
    description: "An open space where books and people meet. Tiered reading areas serve as a community hub.",
    descriptionKo: "책과 사람이 만나는 열린 공간. 계단식 독서 공간이 커뮤니티 허브 역할을 합니다.",
    company: "snp",
  },
  {
    id: "snp-school",
    title: "Future School",
    titleKo: "미래학교",
    location: "Gwangju, Korea",
    locationKo: "광주, 한국",
    year: "2026",
    status: "planning",
    client: "Ministry of Education",
    clientKo: "교육부",
    area: "22,000 m²",
    use: "Education",
    useKo: "교육시설",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=600&fit=crop",
    description: "Innovative learning spaces for future education. Provides flexible modular classrooms and creative collaboration areas.",
    descriptionKo: "미래 교육을 위한 혁신적 학습 공간. 유연한 모듈형 교실과 창의적 협업 공간을 제공합니다.",
    company: "snp",
  },

  // META LOGIC Projects
  {
    id: "ml-datacenter",
    title: "Green Data Center",
    titleKo: "그린 데이터센터",
    location: "Pangyo, Korea",
    locationKo: "판교, 한국",
    year: "2024",
    status: "completed",
    client: "Tech Corp",
    clientKo: "테크 코퍼레이션",
    area: "35,000 m²",
    use: "Data Center / Office",
    useKo: "데이터센터 / 오피스",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop",
    description: "A next-generation data center achieving carbon neutrality. Reached PUE 1.2 through renewable energy and natural cooling systems.",
    descriptionKo: "탄소중립을 실현한 차세대 데이터센터. 재생에너지와 자연 냉각 시스템으로 PUE 1.2를 달성했습니다.",
    company: "metalogic",
    featured: true,
  },
  {
    id: "ml-logistics",
    title: "Smart Logistics Hub",
    titleKo: "스마트 물류허브",
    location: "Pyeongtaek, Korea",
    locationKo: "평택, 한국",
    year: "2023",
    status: "completed",
    client: "Logistics Korea",
    clientKo: "로지스틱스 코리아",
    area: "85,000 m²",
    use: "Logistics / Industrial",
    useKo: "물류 / 산업시설",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=600&fit=crop",
    description: "A mega logistics center with fully automated systems. A future logistics hub operated by robots and AI.",
    descriptionKo: "완전 자동화 물류 시스템을 갖춘 초대형 물류센터. 로봇과 AI가 운영하는 미래형 물류 허브입니다.",
    company: "metalogic",
  },
  {
    id: "ml-factory",
    title: "Smart Factory",
    titleKo: "스마트 팩토리",
    location: "Ulsan, Korea",
    locationKo: "울산, 한국",
    year: "2025",
    status: "in-progress",
    client: "Manufacturing Inc.",
    clientKo: "매뉴팩처링 주식회사",
    area: "120,000 m²",
    use: "Manufacturing",
    useKo: "제조시설",
    image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=800&h=600&fit=crop",
    description: "A smart factory implementing Industry 4.0. Maximized production efficiency through digital twin technology.",
    descriptionKo: "Industry 4.0을 구현한 스마트 공장. 디지털 트윈 기술로 생산 효율을 극대화했습니다.",
    company: "metalogic",
  },

  // Joint Projects (NSM)
  {
    id: "nsm-headquarters",
    title: "NSM Headquarters",
    titleKo: "NSM 본사",
    location: "Seoul, Korea",
    locationKo: "서울, 한국",
    year: "2024",
    status: "completed",
    client: "N/S/M",
    clientKo: "N/S/M",
    area: "52,000 m²",
    use: "Office / Mixed-use",
    useKo: "오피스 / 복합시설",
    image: "https://images.unsplash.com/photo-1554435493-93422e8d2356?w=800&h=600&fit=crop",
    description: "An integrated headquarters where the philosophies of three companies converge. Open workspaces that maximize collaboration and creativity.",
    descriptionKo: "세 회사의 철학이 하나로 모인 통합 본사. 협업과 창의성을 극대화하는 개방형 업무 공간입니다.",
    company: "joint",
    featured: true,
  },
  {
    id: "nsm-masterplan",
    title: "Urban Regeneration",
    titleKo: "도시재생 마스터플랜",
    location: "Incheon, Korea",
    locationKo: "인천, 한국",
    year: "2026",
    status: "planning",
    client: "Incheon Metropolitan City",
    clientKo: "인천광역시",
    area: "250,000 m²",
    use: "Mixed-use / Urban",
    useKo: "복합시설 / 도시개발",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=600&fit=crop",
    description: "A large-scale regeneration project transforming the old downtown into a future mixed-use city. Proposing a sustainable, pedestrian-centered city.",
    descriptionKo: "구도심을 미래형 복합도시로 탈바꿈하는 대규모 재생 프로젝트. 보행 중심의 지속 가능한 도시를 제안합니다.",
    company: "joint",
    featured: true,
  },
  {
    id: "nsm-resort",
    title: "Eco Resort",
    titleKo: "에코 리조트",
    location: "Jeju, Korea",
    locationKo: "제주, 한국",
    year: "2025",
    status: "in-progress",
    client: "Resort Development",
    clientKo: "리조트 개발사",
    area: "78,000 m²",
    use: "Hospitality / Resort",
    useKo: "숙박 / 리조트",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop",
    description: "An eco-friendly resort coexisting with Jeju's nature. Architecture that blends into nature while preserving the terrain.",
    descriptionKo: "제주의 자연과 공존하는 친환경 리조트. 지형을 최대한 보존하며 자연 속에 녹아든 건축을 실현했습니다.",
    company: "joint",
  },
]

export const companies = {
  ndb: {
    name: "NDB",
    fullName: "NDB Architecture",
    description:
      "도시와 건축의 새로운 가능성을 탐구합니다. 지속 가능한 미래를 위한 혁신적인 설계 솔루션을 제공합니다.",
    descriptionEn:
      "We explore new possibilities in city and architecture, delivering innovative design solutions for a sustainable future.",
    founded: "2010",
    location: "Seoul, Korea",
    expertise: ["Commercial", "Residential", "Cultural"],
  },
  snp: {
    name: "SNP",
    fullName: "SNP Design Studio",
    description:
      "공간과 사람의 관계를 디자인합니다. 커뮤니티 중심의 건축으로 더 나은 삶을 만들어갑니다.",
    descriptionEn:
      "We design the relationship between space and people, creating better lives through community‑focused architecture.",
    founded: "2012",
    location: "Seoul, Korea",
    expertise: ["Cultural", "Education", "Public"],
  },
  metalogic: {
    name: "META LOGIC",
    fullName: "META LOGIC Engineering",
    description:
      "기술과 건축의 융합을 선도합니다. 스마트 빌딩과 지속 가능한 인프라 구축에 특화되어 있습니다.",
    descriptionEn:
      "We lead the convergence of technology and architecture, specializing in smart buildings and sustainable infrastructure.",
    founded: "2015",
    location: "Pangyo, Korea",
    expertise: ["Industrial", "Data Center", "Logistics"],
  },
}
